### ISSUE TITLE
Comments and Documentation

### ISSUE THREAD

**Issue by SenhasD** [1to5pc/py-terminal#7]
Consider adding comments or docstrings to explain the purpose of the function and any relevant details about its behavior. This makes the code easier to understand and maintain.

like this:

import time

def boot():
    """
    Initiates the bootloader and prompts the user to boot into pyOS 20.69.

    Returns:
        bool: True if the user chooses to boot into pyOS 20.69, False otherwise.
    """
    print("Initiating bootloader")
    time.sleep(0.3)
    boot_choice = input("Boot into pyOS 20.69? (Y)es/(N)o: ").upper()
    if boot_choice == "Y":
        print("Initiating boot sequence")
        return True
    else:
        print("Aborting boot")
        return False

# Example usage:
booted = boot()
if booted:
    # Continue with boot sequence
    pass
else:
    # Handle aborted boot sequence
    pass

**Comment by SenhasD** [comment]
Example usage is also part of the code. Github somehow messed up markdown

**Comment by senhas-rgb** [comment]
Fixed in the latest commits

**Comment by 1to5pc** [comment]
Fixed in #13
